apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: oficina
type: Opaque
stringData:
  MONGODB_URL: "<MONGODB_URL>"
  MONGODB_DATABASE: "<MONGODB_DATABASE>"
  SECRET_KEY: "<SECRET_KEY>"
  ALGORITHM: "<ALGORITHM>"
  JWT_ISSUER: "<JWT_ISSUER>"
  JWT_AUDIENCE: "<JWT_AUDIENCE>"
  URL_API_OS: "<URL_API_OS>"
