apiVersion: v1
kind: Service
metadata:
  name: oficina-execucao-api-service
  namespace: oficina
spec:
  type: LoadBalancer
  selector:
    app: oficina-execucao-api
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
